// Generated by https://quicktype.io

export interface Job {
  jobCode:           string;
  title:             string;
  description:       string;
  startDate:         string;
  numberOfPositions: number;
}
